version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - forcetypeassert
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - iface
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mirror
    - misspell
    - nilnesserr
    - nilnil
    - nolintlint
    - nonamedreturns
    - prealloc
    - reassign
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: 'pkg/user/(.+)\.go'
        text: "var-naming: avoid package names that conflict with Go standard library package names"

formatters:
  enable:
    - gofumpt
    - goimports
