linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - goerr113
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - lll
    - maintidx
    - misspell
    - nilnil
    - nolintlint
    - nonamedreturns
    - prealloc
    - reassign
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errorlint:
    # Go 1.19 compatibility (https://github.com/sylabs/sif/issues/265).
    errorf-multi: false

  misspell:
    locale: US
